[project]
name = "py_api"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "marshmallow>=3.26.1",
]

[dependency-groups]
dev = ["mypy>=1.15.0", "pytest>=8.3.5", "ruff>=0.11.0"]

[tool.ruff]
extend-select = ["E", "F", "I", "C", "B", "W"]
