name: PR Checks

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Check Formatting
        run: uv run ruff format . --check

      - name: Run Linter
        run: uv run ruff check .

      - name: Run type checks
        run: uv run mypy book_api tests

      - name: Run tests
        run: make test
